name: "BrowserStack flipkart selenium Test"
on: [push, pull_request]
jobs:
  ubuntu-job:
    name: "BrowserStack Test on Ubuntu"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Install Python dependencies"
        uses: actions/setup-python@v2
        with:
          python-version: "3.10" 
      - name: "Install project dependencies"
        run: pip install -r requirements.txt 
      - name: "Run test script on BrowserStack"
        run: browserstack-sdk python ./main.py
        env:
          BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
          BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}